# Generated by Django 4.1 on 2022-08-28 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='likes',
        ),
        migrations.AddField(
            model_name='bird',
            name='searching',
            field=models.ManyToManyField(related_name='searching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bird',
            name='seen',
            field=models.ManyToManyField(related_name='seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
