# Generated by Django 4.1 on 2022-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_author_alter_article_options_article_descriptor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='article',
            name='descriptor',
            field=models.CharField(choices=[('world affairs', 'World Affairs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='secondary_descriptor',
            field=models.CharField(choices=[('world affairs', 'World Affairs')], max_length=20),
        ),
    ]
