# Generated by Django 4.1 on 2022-08-24 23:45

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='guts',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
