# Generated by Django 4.1 on 2022-08-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_article_text_rendered_alter_article_guts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text_rendered',
        ),
        migrations.AlterField(
            model_name='article',
            name='guts',
            field=models.TextField(blank=True),
        ),
    ]
