# Generated by Django 4.1 on 2022-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_bird_family_bird_scientific_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='guts',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bird',
            name='conservation_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bird',
            name='family',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
