# Generated by Django 4.1 on 2022-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_guts_bird_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='conservation_status',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
