# Generated by Django 4.1 on 2022-08-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_bird_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
