# Generated by Django 4.1 on 2022-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_bird_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
