# Generated by Django 4.1 on 2022-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_bird_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={},
        ),
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
